export const ALGERIA_WILAYAS = [
  "Adrar",
  "Aïn Defla",
  "Aïn Témouchent",
  "Algiers",
  "Batna",
  "Béchar",
  "Béjaïa",
  "Biskra",
  "Blida",
  "Bordj Bou Arréridj",
  "Bouira",
  "Boumerdès",
  "Chlef",
  "Constantine",
  "Djelfa",
  "El Bayadh",
  "El Oued",
  "El Tarf",
  "Ghardaïa",
  "Guelma",
  "Illizi",
  "Jijel",
  "Khenchela",
  "Laghouat",
  "Mascara",
  "Médéa",
  "Mila",
  "Mostaganem",
  "Msila",
  "Naâma",
  "Oran",
  "Ouargla",
  "Oum El Bouaghi",
  "Relizane",
  "Saïda",
  "Sétif",
  "Sidi Bel Abbès",
  "Skikda",
  "Souk Ahras",
  "Tamanghasset",
  "Tébessa",
  "Tiaret",
  "Timimoun",
  "Tindouf",
  "Tipaza",
  "Tissemsilt",
  "Tizi Ouzou",
  "Tlemcen",
  "Touggourt",
] as const;

export type Wilaya = (typeof ALGERIA_WILAYAS)[number];
